import React, { useEffect, useRef, useState } from 'react'
import PoemCard from './PoemCard'
import { FiTrash2, FiHeart, FiCopy, FiShare2, FiDownload } from 'react-icons/fi'
import html2canvas from 'html2canvas'

export default function PoemList({ saved, setSaved, refForNewest }) {
  const [sharingId, setSharingId] = React.useState(null)
  const listRef = useRef(null)

  useEffect(() => {
    if (refForNewest && refForNewest.current && listRef.current) {
      listRef.current.scrollIntoView({ behavior: 'smooth' })
    }
  }, [saved, refForNewest])

  function handleDelete(idx) {
    setSaved(prev => prev.filter((_, i) => i !== idx))
  }

  async function handleShare(poem) {
    const cardElement = document.getElementById(`poem-card-${poem.id}`)
    if (!cardElement) return

    setSharingId(poem.id)
    try {
      const canvas = await html2canvas(cardElement, {
        scale: 3, // Even higher quality for sharing
        backgroundColor: '#111827', // Matching gray-900
        useCORS: true,
        logging: false,
        onclone: (clonedDoc) => {
          const clonedCard = clonedDoc.getElementById(`poem-card-${poem.id}`)
          if (clonedCard) {
            // Remove glass effect which doesn't render well in html2canvas
            clonedCard.style.backdropFilter = 'none'
            clonedCard.style.webkitBackdropFilter = 'none'
            // Ensure background is more solid for the capture
            clonedCard.style.backgroundColor = 'rgba(17, 24, 39, 0.8)'
            clonedCard.style.border = '1px solid rgba(255, 255, 255, 0.1)'
          }
        }
      })

      canvas.toBlob(async (blob) => {
        if (!blob) {
          setSharingId(null)
          return
        }

        const file = new File([blob], `poem-${poem.id}.png`, { type: 'image/png' })

        // Check for Web Share API support
        const canShare = navigator.canShare && navigator.canShare({ files: [file] })

        if (canShare) {
          try {
            await navigator.share({
              files: [file],
              title: 'My AI Poem',
              text: 'Check out this poem generated by AI!',
            })
          } catch (error) {
            if (error.name !== 'AbortError') {
              console.error('Error sharing:', error)
              alert('Could not open share menu. Downloading image instead.')
              downloadBlob(blob, poem.id)
            }
          }
        } else {
          // Fallback: Download the image
          downloadBlob(blob, poem.id)
          // Simple feedback
          alert('Share menu not supported on this browser. Poem image downloaded!')
        }
        setSharingId(null)
      }, 'image/png')
    } catch (err) {
      console.error('Failed to capture poem card:', err)
      setSharingId(null)
    }
  }

  function downloadBlob(blob, id) {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `poem-${id}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (!saved || saved.length === 0) {
    return (
      <section className="mt-8">
        <div className="p-8 rounded-2xl glass text-center">
          <h4 className="text-lg font-medium">No previous poems</h4>
          <p className="text-gray-400">Generate and save poems — they appear here as a collection of your recent discoveries.</p>
        </div>
      </section>
    )
  }

  return (
    <section className="mt-8">
      <h4 className="mb-4 text-sm text-gray-300">Previous Poems</h4>
      <div ref={listRef} className="flex flex-col">
        {saved.map((p, idx) => (
          <div key={p.id} className="relative">
            <PoemCard poem={p} extraActions={(
              <div className="flex gap-2 mt-3">
                <button
                  title={navigator.canShare ? "Share to Instagram/Socials" : "Download to share on Instagram"}
                  onClick={() => handleShare(p)}
                  disabled={sharingId === p.id}
                  className={`p-2 rounded-md transition-colors ${sharingId === p.id ? 'bg-pink-900' : 'bg-pink-700 hover:bg-pink-600'}`}
                >
                  {sharingId === p.id ? (
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  ) : (
                    navigator.canShare ? <FiShare2 /> : <FiDownload />
                  )}
                </button>
                <button className="p-2 rounded-md bg-gray-800 hover:bg-gray-700"><FiHeart /></button>
                <button onClick={() => navigator.clipboard.writeText(p.lines.join('\n'))} className="p-2 rounded-md bg-gray-800"><FiCopy /></button>
                <button onClick={() => handleDelete(idx)} className="p-2 rounded-md bg-red-700"><FiTrash2 /></button>
              </div>
            )} />
          </div>
        ))}
      </div>
    </section>
  )
}
